### Importing Dependencies

In [29]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, confusion_matrix

### Reading Data

In [8]:
df = pd.read_csv('sonar.csv', header=None)
# df.head()
# df.shape
df.describe()

,0,1,2,3,4,5,6,7,8,9,...,50,51,52,53,54,55,56,57,58,59
count,208.000000,208.000000,208.000000,208.000000,208.000000,208.000000,208.000000,208.000000,208.000000,208.000000,...,208.000000,208.000000,208.000000,208.000000,208.000000,208.000000,208.000000,208.000000,208.000000,208.000000
mean,0.029164,0.038437,0.043832,0.053892,0.075202,0.104570,0.121747,0.134799,0.178003,0.208259,...,0.016069,0.013420,0.010709,0.010941,0.009290,0.008222,0.007820,0.007949,0.007941,0.006507
std,0.022991,0.032960,0.038428,0.046528,0.055552,0.059105,0.061788,0.085152,0.118387,0.134416,...,0.012008,0.009634,0.007060,0.007301,0.007088,0.005736,0.005785,0.006470,0.006181,0.005031
min,0.001500,0.000600,0.001500,0.005800,0.006700,0.010200,0.003300,0.005500,0.007500,0.011300,...,0.000000,0.000800,0.000500,0.001000,0.000600,0.000400,0.000300,0.000300,0.000100,0.000600
25%,0.013350,0.016450,0.018950,0.024375,0.038050,0.067025,0.080900,0.080425,0.097025,0.111275,...,0.008425,0.007275,0.005075,0.005375,0.004150,0.004400,0.003700,0.003600,0.003675,0.003100
50%,0.022800,0.030800,0.034300,0.044050,0.062500,0.092150,0.106950,0.112100,0.152250,0.182400,...,0.013900,0.011400,0.009550,0.009300,0.007500,0.006850,0.005950,0.005800,0.006400,0.005300
75%,0.035550,0.047950,0.057950,0.064500,0.100275,0.134125,0.154000,0.169600,0.233425,0.268700,...,0.020825,0.016725,0.014900,0.014500,0.012100,0.010575,0.010425,0.010350,0.010325,0.008525
max,0.137100,0.233900,0.305900,0.426400,0.401000,0.382300,0.372900,0.459000,0.682800,0.710600,...,0.100400,0.070900,0.039000,0.035200,0.044700,0.039400,0.035500,0.044000,0.036400,0.043900

In [9]:
df[60].value_counts()

60
M    111
R     97
Name: count, dtype: int64

In [12]:
df.groupby(60).mean()

,0,1,2,3,4,5,6,7,8,9,...,50,51,52,53,54,55,56,57,58,59
60,,,,,,,,,,,,,,,,,,,,,
M,0.034989,0.045544,0.050720,0.064768,0.086715,0.111864,0.128359,0.149832,0.213492,0.251022,...,0.019352,0.016014,0.011643,0.012185,0.009923,0.008914,0.007825,0.009060,0.008695,0.006930
R,0.022498,0.030303,0.035951,0.041447,0.062028,0.096224,0.114180,0.117596,0.137392,0.159325,...,0.012311,0.010453,0.009640,0.009518,0.008567,0.007430,0.007814,0.006677,0.007078,0.006024

### Separating Features and Target

In [ ]:
X = df.iloc[:, :-1] # Features
y = df.iloc[:, -1]  # Target

### Training the Model

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42)
logistic_reg = LogisticRegression()
logistic_reg.fit(X_train, y_train)

['M' 'R' 'R' 'R' 'M' 'R' 'R' 'M' 'R' 'M' 'M' 'R' 'R' 'M' 'M' 'M' 'M' 'M'
 'M' 'R' 'M' 'M' 'R' 'R' 'R' 'R' 'R' 'R' 'M' 'M' 'M' 'R' 'R' 'M' 'M' 'R'
 'M' 'R' 'M' 'M' 'R' 'R']

### Model Accuracy

In [ ]:
# Accuracy on training data

X_train_pred = logistic_reg.predict(X_train)
training_data_accuracy = accuracy_score(X_train_pred, y_train)

print(f"Training data accuracy: {training_data_accuracy}")

Training data accuracy: 0.8373493975903614

In [32]:
# Accuracy on test data

X_test_pred = logistic_reg.predict(X_test)
test_data_accuracy = accuracy_score(X_test_pred, y_test)

print(f"Test data accuracy: {test_data_accuracy}")

Test data accuracy: 0.7857142857142857

### Making the Predictive System

In [39]:
input_data = (0.0200, 0.0371, 0.0428, 0.0207, 0.0954, 0.0986, 0.1539, 0.1601, 0.3109, 0.2111, 0.1609, 0.1582, 0.2238, 0.0645, 0.0660, 0.2273, 0.3100, 0.2999, 0.5078, 0.4797, 0.5783, 0.5071, 0.4328, 0.5550, 0.6711, 0.6415, 0.7104, 0.8080, 0.6791,
              0.3857, 0.1307, 0.2604, 0.5121, 0.7547, 0.8537, 0.8507, 0.6692, 0.6097, 0.4943, 0.2744, 0.0510, 0.2834, 0.2825, 0.4256, 0.2641, 0.1386, 0.1051, 0.1343, 0.0383, 0.0324, 0.0232, 0.0027, 0.0065, 0.0159, 0.0072, 0.0167, 0.0180, 0.0084, 0.0090, 0.0032)

# changing the input_data into a numpy array since processing a numpy array is faster
input_data = np.asarray(input_data)

# reshape the array for better training of the model
# input_data.reshape(1, -1) converts a flat vector of features into the correct 2D shape (one row, many columns) so that the ML model can make a prediction.
input_data = input_data.reshape(1, -1)

prediction = logistic_reg.predict(input_data)

print(f"Prediction: {prediction}")

if(prediction[0] == 'R'):
    print("The object is a Rock")
else:
    print("The object is a Mine")

Prediction: ['R']
The object is a Rock

### Saving the Model

In [40]:
import pickle
filename = 'Rock_Mine.sav'
pickle.dump(logistic_reg, open(filename, 'wb'))

### Loading the Saved Model

In [41]:
load = pickle.load(open(filename, 'rb'))

In [42]:
input_data = (0.0200, 0.0371, 0.0428, 0.0207, 0.0954, 0.0986, 0.1539, 0.1601, 0.3109, 0.2111, 0.1609, 0.1582, 0.2238, 0.0645, 0.0660, 0.2273, 0.3100, 0.2999, 0.5078, 0.4797, 0.5783, 0.5071, 0.4328, 0.5550, 0.6711, 0.6415, 0.7104, 0.8080, 0.6791,
              0.3857, 0.1307, 0.2604, 0.5121, 0.7547, 0.8537, 0.8507, 0.6692, 0.6097, 0.4943, 0.2744, 0.0510, 0.2834, 0.2825, 0.4256, 0.2641, 0.1386, 0.1051, 0.1343, 0.0383, 0.0324, 0.0232, 0.0027, 0.0065, 0.0159, 0.0072, 0.0167, 0.0180, 0.0084, 0.0090, 0.0032)

# changing the input_data into a numpy array since processing a numpy array is faster
input_data = np.asarray(input_data)

# reshape the array for better training of the model
# input_data.reshape(1, -1) converts a flat vector of features into the correct 2D shape (one row, many columns) so that the ML model can make a prediction.
input_data = input_data.reshape(1, -1)

prediction = load.predict(input_data)

# print(f"Prediction: {prediction}")

if (prediction[0] == 'R'):
    print("The object is a Rock")
else:
    print("The object is a Mine")

The object is a Rock